version: '2.1'

services:
  shell:
    build:
      context: .
      dockerfile: ./shell/Dockerfile
    image: user-shell
    container_name: user-shell
    volumes:
      - .:/project/sawtooth-supply
    command: |
      bash -c "
        protogen
        tail -f /dev/null"
    networks:
      - vchain_vChain
  user-tp:
    build:
      context: .
      dockerfile: ./processor/Dockerfile
    image: user-tp
    container_name: user-tp
    volumes:
      - '.:/project/sawtooth-supply'
    depends_on:
      - shell
    command: |
      bash -c "
        sleep 1
        tp -v -C tcp://validator:4004"
    networks:
      - vchain_vChain
  user-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
    image: user-rest-api
    container_name: user-rest-api
    volumes:
      - .:/project/sawtooth-supply
    ports:
      - '8096:8096'
    depends_on:
      - shell
    command: |
      bash -c "
        rest-api \
          -B vbml-sawtooth-rest-api:8096 \
          -C validator:4004\
          -vv"
    networks:
      - vchain_vChain
networks:
  vchain_vChain:
    external: true
